-- +goose Up
-- +goose StatementBegin
CREATE TABLE SITE_USER
(
    ID            UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    EMAIL_ADDRESS TEXT NOT NULL UNIQUE,
    PHONE_NUMBER  TEXT NOT NULL UNIQUE,
    PASSWORD      TEXT NOT NULL
);

CREATE TABLE COUNTRY
(
    ID           UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    COUNTRY_NAME TEXT NOT NULL
);

CREATE TABLE ADDRESS
(
    ID            UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    UNIT_NUMBER   TEXT NOT NULL,
    STREET_NUMBER TEXT NOT NULL,
    ADDRESS_LINE1 TEXT NOT NULL,
    ADDRESS_LINE2 TEXT,
    CITY          TEXT NOT NULL,
    REGION        TEXT NOT NULL,
    POSTAL_CODE   TEXT NOT NULL,
    COUNTRY_ID    UUID NOT NULL REFERENCES COUNTRY (ID)
);

CREATE TABLE USER_ADDRESS
(
    USER_ID    UUID REFERENCES SITE_USER (ID),
    ADDRESS_ID UUID REFERENCES ADDRESS (ID),
    IS_DEFAULT BOOLEAN NOT NULL
);

CREATE TABLE PRODUCT_CATEGORY
(
    ID              UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PARENT_CATEGORY UUID NOT NULL REFERENCES PRODUCT_CATEGORY (ID),
    CATEGORY_NAME   TEXT NOT NULL
);

CREATE TABLE PROMOTION
(
    ID            UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID() NOT NULL,
    NAME          TEXT                                       NOT NULL,
    DESCRIPTION   TEXT                                       NOT NULL,
    DISCOUNT_RATE SMALLINT                                   NOT NULL,
    START_DATE    DATE                                       NOT NULL,
    END_DATE      DATE                                       NOT NULL

        CONSTRAINT CK_PROMOTION_START_DATE CHECK ( START_DATE > NOW() ),
    CONSTRAINT CK_PROMOTION_END_DATE CHECK ( END_DATE > START_DATE )


);

CREATE TABLE PROMOTION_CATEGORY
(
    CATEGORY_ID  UUID NOT NULL REFERENCES PRODUCT_CATEGORY (ID),
    PROMOTION_ID UUID NOT NULL REFERENCES PROMOTION (ID)
);

CREATE TABLE PRODUCT
(
    ID            UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CATEGORY_ID   UUID NOT NULL REFERENCES PRODUCT_CATEGORY (ID),
    NAME          TEXT NOT NULL,
    DESCRIPTION   TEXT NOT NULL,
    PRODUCT_IMAGE TEXT NOT NULL
);

CREATE TABLE VARIATION
(
    ID          UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CATEGORY_ID UUID REFERENCES PRODUCT_CATEGORY (ID),
    NAME        TEXT NOT NULL
);


CREATE TABLE VARIATION_OPTION
(
    ID           UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    VARIATION_ID UUID NOT NULL REFERENCES VARIATION (ID),
    VALUE        TEXT NOT NULL
);

CREATE TABLE PRODUCT_ITEM
(
    ID            UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PRODUCT_ID    UUID NOT NULL REFERENCES PRODUCT (ID),
    SKU           TEXT NOT NULL,
    QTY_IN_STOCK  INT  NOT NULL,
    PRODUCT_IMAGE TEXT NOT NULL,
    PRICE         MONEY
        CONSTRAINT CK_PRODUCT_ITEM_QTY_IN_STOCK CHECK ( QTY_IN_STOCK > 0 ),
    CONSTRAINT CK_PRODUCT_ITEM_PRICE CHECK ( PRICE::NUMERIC > 0 )
);

CREATE TABLE PRODUCT_CONFIGURATION
(
    PRODUCT_ITEM_ID     UUID NOT NULL REFERENCES PRODUCT_ITEM (ID),
    VARIATION_OPTION_ID UUID NOT NULL REFERENCES VARIATION_OPTION (ID)
);

CREATE TABLE SHOPPING_CART
(
    ID      UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID NOT NULL REFERENCES SITE_USER (ID)
);

CREATE TABLE SHOPPING_CART_ITEM
(
    ID              UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CART_ID         UUID NOT NULL REFERENCES SHOPPING_CART (ID),
    PRODUCT_ITEM_ID UUID NOT NULL REFERENCES PRODUCT_ITEM (ID),
    QTY             INT  NOT NULL
        CONSTRAINT CK_SHOPPING_CART_ITEM_QTY CHECK ( QTY > 0 )
);


CREATE TABLE PAYMENT_TYPE
(
    ID    UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    VALUE TEXT NOT NULL
);

CREATE TABLE USER_PAYMENT_METHOD
(
    ID              UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID         UUID    NOT NULL REFERENCES SITE_USER (ID),
    PAYMENT_TYPE_ID UUID    NOT NULL REFERENCES PAYMENT_TYPE (ID),
    PROVIDER        TEXT    NOT NULL,
    ACCOUNT_NUMBER  TEXT    NOT NULL,
    EXPIRY_DATE     TEXT    NOT NULL,
    IS_DEFAULT      BOOLEAN NOT NULL
);

CREATE TABLE SHIPPING_METHOD
(
    ID    UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NAME  TEXT  NOT NULL,
    PRICE MONEY NOT NULL
        CONSTRAINT CK_SHIPPING_METHOD_PRICE CHECK ( PRICE::NUMERIC > 0 )
);

CREATE TABLE ORDER_STATUS
(
    ID     UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    STATUS TEXT NOT NULL
);

CREATE TABLE SHOP_ORDER
(
    ID                UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID           UUID  NOT NULL REFERENCES SITE_USER (ID),
    ORDER_DATE        DATE  NOT NULL   DEFAULT NOW(),
    PAYMENT_METHOD_ID UUID  NOT NULL REFERENCES USER_PAYMENT_METHOD (ID),
    SHIPPING_ADDRESS  UUID  NOT NULL REFERENCES ADDRESS (ID),
    SHIPPING_METHOD   UUID  NOT NULL REFERENCES SHIPPING_METHOD (ID),
    ORDER_TOTAL       MONEY NOT NULL,
    ORDER_STATUS      UUID  NOT NULL REFERENCES ORDER_STATUS (ID)

);

CREATE TABLE USER_REVIEW
(
    ID                 UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID            UUID NOT NULL REFERENCES SITE_USER (ID),
    ORDERED_PRODUCT_ID UUID NOT NULL REFERENCES SHOP_ORDER (ID),
    RATING_VALUE       INT  NOT NULL,
    COMMENT            TEXT
        CONSTRAINT CK_USER_REVIEW_RATING_VALUE CHECK ( RATING_VALUE BETWEEN 0 AND 5)

);



-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
